name: Publish Release
on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      ref:
        description: "Git Tag or Ref to publish from. Default to main, but you can specify a tag to retrigger publishing"
        required: true
        default: 'main'

jobs:
  publish:
    if: ${{ github.repository == 'facebookincubator/dataclassgenerate'}}
    runs-on: [ubuntu-latest]
    env:
      GRADLE_OPTS: -Dorg.gradle.parallel=false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@v2

      - name: Publish to Maven Local
        run: ./gradlew publishAllToMavenLocal
        env:
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PWD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PWD }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 'snapshot-artifacts'
          path: '~/.m2/repository/'

      - name: Publish the Artifact to Maven Central
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PWD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PWD }}

      - name: Publish the Gradle Plugin to Maven Central
        run: ./gradlew -p gradleplugin publishPlugins
        env:
          ORG_GRADLE_PROJECT_gradle.publish.key: ${{ secrets.ORG_GRADLE_PROJECT_GRADLE_PUBLISH_KEY }}
          ORG_GRADLE_PROJECT_gradle.publish.secret: ${{ secrets.ORG_GRADLE_PROJECT_GRADLE_PUBLISH_SECRET }}
          ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PWD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PWD }}
