name: Publish Snapshot
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    if: ${{ github.repository == 'facebookincubator/dataclassgenerate'}}
    runs-on: [ubuntu-latest]
    env:
      GRADLE_OPTS: -Dorg.gradle.parallel=false

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Publish to Maven Local
        run: ./gradlew publishAllToMavenLocal
        env:
          ORG_GRADLE_PROJECT_USE_SNAPSHOT: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'snapshot-artifacts'
          path: '~/.m2/repository/'

      - name: Publish to the Snapshot Repository
        run: ./gradlew publishAllToSonatype
        env:
          ORG_GRADLE_PROJECT_NEXUS_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_NEXUS_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_USE_SNAPSHOT: true
